README.md, deploy/crds/keda.k8s.io_kedacontrollers_crd.yaml, deploy/crds/keda.k8s.io_v1alpha1_kedacontroller_cr.yaml, deploy/resources/12-operator.yaml, pkg/apis/keda/v1alpha1/kedacontroller_types.go, pkg/controller/kedacontroller/kedacontroller_controller.go, pkg/controller/kedacontroller/transform/transform.go
=> generalized replacing container arguments

.github/workflows/master-build.yml, .github/workflows/nightly-tests.yml, .github/workflows/pr-tests.yml, Makefile, controllers/kedacontroller_controller.go, controllers/kedacontroller_controller_test.go, controllers/suite_test.go, go.sum
Fixes #19 
- added e2e tests
- refactored existing unit test to use [ginkgo](https://github.com/onsi/ginkgo) library
- updated testing in .github workflows
Signed-off-by: Samuel Macko <samuel.macko.sm@gmail.com>
=> added e2e tests

.github/workflows/release-build.yml
=> Go stuff is not needed in release build action

main.go
By mistake this was changed during #96
=> use `olm-operator.keda.sh` as `LeaderElectionID`

Makefile
```
time="2022-05-13T13:48:51Z" level=error msg="permissive mode disabled" bundles="[ghcr.io/kedacore/keda-olm-operator-bundle:main]" error="Invalid bundle keda.v2.7.0, bundle specifies a non-existent replacement keda.v2.6.0"
Error: Invalid bundle keda.v2.7.0, bundle specifies a non-existent replacement keda.v2.6.0
```
=> disable 'replaces' field, as the testing bundle doesn't replace anything

.github/workflows/main-build.yml, .github/workflows/nightly-tests.yml
fix main build & nightly after running image update (no longer has brew by default)
https://github.com/actions/runner-images/issues/6283
=> fix: main & nightly builds after running image updates

Makefile
during deployment tests, the workflow gets stuck on deleting olm namespace -> specifically the namespace gets stuck in state "terminating". Since these run in separate containters, dont enforce olm namespace deletion -> the destruction of the container will take care of it
=> dont delete olm ns after depl-test

.github/workflows/version-diff.yml, Makefile
- fix version-diff workflow by adding initial conditional check -> run only if `keda/` directories dont match AKA if new directory was added
- fix `Makefile` so workflows dont hang
=> Fix wf new

Makefile
Because make will run ifeq shell commands on every invocation, every target
causes kubectl to be invoked to list namespaces, even targets which never
would have reached the targets in question.  Instead, update such targets
to use kubectl apply instead of kubectl create so that creation will succeed
even if the namespace already exists.
=> Remove extra kubectl invocations

README.md, bundle/manifests/keda.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/keda.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/keda/kedacontroller_controller.go, controllers/keda/util/util.go, keda/2.9.3/manifests/keda.v2.9.3.clusterserviceversion.yaml, resources/keda.yaml
This change introduces the setup to enable the metric collection if the monitoring CRDs are present in the cluster.
- [x ] Commits are signed with Developer Certificate of Origin (DCO)
=> Add support for Prometheus monitoring stack

RELEASE-PROCESS.md
=> Update release process to point to GHCR instead of DockerHub

RELEASE-PROCESS.md
=> Remove openshift community operator repo from release instructions as it is deprecated

controllers/keda/kedacontroller_controller.go, controllers/keda/transform/transform.go, resources/keda-olm-operator.yaml
Also, fix namespace for prometheus monitoring objects
=> Add OpenShift CA bundle when deployed on OpenShift

controllers/keda/kedacontroller_controller.go, controllers/keda/suite_test.go, controllers/keda/transform/transform.go, controllers/keda/util/util.go, main.go
=> Remove SeccompProfile RuntimeDefault from securityContext on old OpenShift clusters

controllers/keda/kedacontroller_controller.go, controllers/keda/transform/transform.go
A user noticed that the OLM operator was trying and failing to create a rolebinding in the `kube-system` namespace because it tries to add an owner reference to the kedacontroller object from a different namespace.
```
$ kubectl get events -n kube-system|grep -i keda
4m51s       Warning   OwnerRefInvalidNamespace   rolebinding/keda-auth-reader   ownerRef [keda.sh/v1alpha1/KedaController, namespace: kube-system, name: keda, uid: 1e9a6cd3-17e8-4dec-832f-64ab6db759fe] does not exist in namespace "kube-system"
```
This change makes it so that the OLM operator will only set the owner reference on objects in the same namespace as the kedacontroller object.
=> Don't set ownerReference on cluster-scoped and cross-namespace objects

.github/workflows/nightly-tests.yml
=> Make nightly tests more robust

README.md
I was linked to this repository, and the README.md assumes you already know what "KEDA" is.  Make it a hyperlink *and* expand the acronym to be friendlier to people who don't yet know what it is.
Signed-off-by: Colin Walters <walters@verbum.org>
=> README.md: Link to main  site

controllers/keda/kedacontroller_controller.go
This is a follow-up PR to #201 which was incomplete
=> Use KEDA-specific annotation name for last config, part 2

README.md, bundle/manifests/keda.clusterserviceversion.yaml, config/manifests/bases/keda.clusterserviceversion.yaml, main.go
In #192 there was an attempt to change the CSV to change the installMode from `OwnNamepsace` to `AllNamespaces`, but that change was lost during the next bundle re-generation. This PR re-makes that change in both the config and the bundle, but allows the operator to be installed in either mode. This provides flexibility allowing the operator to be installed into existing namespaces, potentially with other operators present, where the `OperatorGroup` is already present and annotated to require one or the other.
With the installMode `AllNamespaces`, `WATCH_NAMESPACE` may not be set especially in cases where the operator is installed to an existing namespace with an existing `operatorgroup`.  This change allows the KEDA OLM operator to work whether it is run with a `WATCH_NAMESPACE`
env var …
=> Use installed namespace if WATCH_NAMESPACE not set

Makefile
Based on a discussion on slack: https://kubernetes.slack.com/archives/C01JGDP8MB8/p1697551115191649
=> Kubectl server side apply

bundle/manifests/keda.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/keda.clusterserviceversion.yaml, hack/relprep.sh
Also:
* make CRD extraction more robust, to handle more than just examples.keda.sh CRDs
* notice when there are missing CRDs in the bundle generation inputs
* manually sync some of the manifest CSV fields and the inputs to the
generated bundle CSV's fields so that the new check passes
Notes for reviewers:
While doing the upstream 2.12.1 release, I noticed a little weirdness in the KEDA OLM operator's `hack/relprep.sh` script. Namely, that it isn't keeping `config/manifests/bases/keda.clusterserviceversion.yaml` and `bundle/manifests/keda.clusterserviceversion.yaml` in sync. Apparently, the former doesn't get updated by the `operator-sdk generate kustomize manifests -q` command like I thought it did, and the latter does get updated, but is only used for our manual testing workflow (when …
=> Have relprep.sh check to see if bundle & manifest CSVs are in sync

.github/workflows/main-build.yml, .github/workflows/nightly-tests.yml, .github/workflows/pr-tests.yml, .github/workflows/release-build.yml, .golangci.yml, Dockerfile, README.md, controllers/keda/configmap_controller.go, controllers/keda/secret_controller.go, controllers/keda/transform/transform.go, go.mod, go.sum, hack/kedacontroller.yaml, hack/relprep.sh
Several changes related to builds and the release process, plus a bonus, unrelated docs fix:
* Switch from keda build-tools image to keda-tools image since the KEDA build-tools image is no longer being updated and the keda-tools image replaces it.
* have `hacks/relprep.sh` detect and use the same version of k8s libraries as KEDA is using, for a given version (See #215 )
* fix new CSV comparison check by running it later in the process so that the comparison will be valid.
* Clean up the examples of omitStages to be a list, not string
Fixes #215
=> Switch from keda build-tools image to keda-tools image

resources/keda-olm-operator.yaml
In our 2.11.2 release https://github.com/kedacore/keda-olm-operator/pull/205 we:
- retired the `9022` metrics port, and replaced it with `8080`, the old http port. 
- updated the service with the port name "metrics"
However: 
-  it looks like we missed updating the ServiceMonitor, which still references the port as "http"
- the prometheus target for `keda-metrics-apiserver` isn't working because it can't find a port named "http" anymore.
Therefore: 
- This updates the ServiceMonitor so the servicemonitor port name matches the service port name. 
Fixes #
=> Fix keda-metrics-apiserver ServiceMonitor port

.github/workflows/main-build.yml
This should fix failures of main build workflow with errors like:
```
Error: signing [ghcr.io/kedacore/keda-olm-operator:main]: getting signer: getting key from Fulcio: verifying SCT: updating local metadata and targets: error updating to TUF remote mirror: invalid key
```
=> Update cosign-installer for main builds

controllers/keda/util/util.go, controllers/keda/util/util_suite_test.go, controllers/keda/util/util_test.go
=> Handle non-numeric suffix when detecting OpenShift minor version

controllers/keda/kedacontroller_controller_test.go
This functionality test has been failing since we did our last bump. 
It was honestly never really testing anything because it never waited for the deployments, we were mostly getting lucky and not checking errors. See this run for an example of the old "tests nothing and succeeds" behavior: https://github.com/kedacore/keda-olm-operator/actions/runs/8209089746/job/22472571935
This change is basically: 
- add a `testCase` annotation to the deployment containing the test case name when we attempt an attribute change
- wait for that annotation to show up after we apply our kedacontroller, signifying that the controller processed the deployment
- _then_ we can check for the attribute we changed and make sure it handled it properly for our specific testcase
I'm not in love with this fix, but I …
=> Fix functionality (audit, loglevel) tests to actually wait for changes

hack/relprep.sh
We're currently missing an example for the new cloudeventsource CRD. Hopefully this change will keep that from happening in the future. As long as https://github.com/kedacore/keda/pull/5921 merges before the 2.15 release, this will clean things up for that release.
=> Sync sample CRs from main repo during releases

controllers/keda/kedacontroller_controller.go
Since OLM installs the operator to an existing namespace, there is little (no?) value in having this operator try to manage the namespace where it is already running. Also, we have an apparent bug where we always create/manage the `keda` namespace even if the operator is running in a different namespace.
=> Prevent namespace creation/modification when installing via OLM

hack/relprep.sh
Previously the relprep script assumed we always wanted the latest go toolchain, but that might not be the case for point releases. Now we will explicitly match what KEDA used for a given release.
Same goes for `sigs.k8s.io/controller-runtime`, `sigs.k8s.io/controller-runtime/tools/setup-envtest` and `sigs.k8s.io/controller-tools`.
=> Fix hack/relprep.sh script to match KEDA repo

bundle/manifests/keda.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/keda.clusterserviceversion.yaml, keda/2.14.1/manifests/keda.v2.14.1.clusterserviceversion.yaml, keda/2.15.0/manifests/keda.v2.15.0.clusterserviceversion.yaml
- The operand's root is set to read only, but the operator isn't, which is causing things like the trivy scanner to complain about it as "severity high" misconfiguration:
```
"Type": "Kubernetes Security Check",
"ID": "KSV014",
"AVDID": "AVD-KSV-0014",
"Title": "Root file system is not read-only",
"Description": "An immutable root file system prevents applications from writing to their local disk. This can limit intrusions, as attackers will not be able to tamper with the file system or write foreign executables to disk.",
"Message": "Container 'custom-metrics-autoscaler-operator' of Pod 'custom-metrics-autoscaler-operator-5b6fb58767-zmrvr' should set 'securityContext.readOnlyRootFilesystem' to true",
"Namespace": "builtin.kubernetes.KSV014",
"Query": …
```
=> Set "readOnlyRootFilesystem: true" in operator pod template to match operand
