kedacore/keda-olm-operator

- LICENSE
Relates to https://github.com/kedacore/keda/issues/658
> Provide license for CNCF

- README.md
> Update Readme for operator-sdk v0.17

- pkg/controller/kedacontroller/kedacontroller_controller.go
- pkg/controller/kedacontroller/kedacontroller_finalizer.go
> use Patch() instead of Update() on KedaController CR

- deploy/role.yaml
- pkg/controller/configmap/configmap_controller.go
- pkg/controller/kedacontroller/kedacontroller_controller.go
- pkg/controller/secret/secret_controller.go
- pkg/controller/util/util.go
- if not running on openshift use generated self-signed cert for KEDA Metrics Server
> Use Service CA Operator only on Openshift

- deploy/olm-catalog/keda/1.4.1/keda.v1.4.1.clusterserviceversion.yaml
- deploy/olm-catalog/keda/1.4.1/kedacontrollers.keda.k8s.io.crd.yaml
- deploy/olm-catalog/keda/1.4.1/scaledobjects.keda.k8s.io.crd.yaml
- deploy/olm-catalog/keda/1.4.1/triggerauthentications.keda.k8s.io.crd.yaml
- deploy/olm-catalog/keda/keda.package.yaml
- deploy/olm-catalog/operator-source.yaml
- deploy/resources/00-namespace.yaml
- deploy/resources/01-service_account.yaml
- deploy/resources/10-cluster_role.yaml
- deploy/resources/11-role_binding.yaml
- deploy/resources/12-operator.yaml
- deploy/resources/20-metrics-cluster_role.yaml
- deploy/resources/21-metrics-role_binding.yaml
- deploy/resources/22-metrics-deployment.yaml
- deploy/resources/23-metrics-service.yaml
- deploy/resources/24-metrics-api_service.yaml
- deploy/resources/crds/keda.k8s.io_v1alpha1_scaledobject_cr.yaml
- deploy/resources/crds/keda.k8s.io_v1alpha1_triggerauthentication_cr.yaml
- version/version.go
> KEDA v1.4.1

- .github/workflows/master-build.yml
> master push github action

- Makefile
- go.sum
- test/main_test.go
> basic e2e test

- .github/workflows/master-build.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/nightly-unit-test.yml
- .github/workflows/pr-tests.yml
- Makefile
> Unit action

- .github/workflows/master-build.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/pr-tests.yml
> github actions for tests

- .github/workflows/master-build.yml
Jobs in master-build action are run sequentially
> small fix in actions

- .github/workflows/master-build.yml
> use go 1.14 in master test step

- README.md
> add badges with build and nightly tests status

- .github/workflows/master-build.yml
- .gitignore
- Dockerfile
- Makefile
- api/v1alpha1/groupversion_info.go
- api/v1alpha1/kedacontroller_types.go
- config/default/kustomization.yaml
- config/manager/kustomization.yaml
- controllers/configmap_controller.go
- controllers/kedacontroller_controller.go
- controllers/kedacontroller_controller_test.go
- controllers/kedacontroller_finalizer.go
- controllers/secret_controller.go
- controllers/suite_test.go
- auto create keda namespace
- go 1.15.3 
- fixed logging mesages in controllers
- improved Version setting and Manifests manipulation in Makefile
- minor fixes & chores
> auto create keda namespace, go 1.15.3 & minor fixes

- .gitignore
- config/manager/manager.yaml
- main.go
- version/version.go
- add resource limits
- add probes
- print Git commit
> add resource limits, probes

- README.md
sample still needs to be updated
> update Readme for KEDA v2

- .github/workflows/master-build.yml
> fetch .git folder in the workflow

- Dockerfile
- Makefile
- api/v1alpha1/kedacontroller_types.go
- bundle/manifests/keda-olm-operator.clusterserviceversion.yaml
- bundle/manifests/keda-olm-operator_v1_serviceaccount.yaml
- bundle/manifests/keda.sh_kedacontrollers.yaml
- bundle/manifests/keda.sh_scaledjobs.yaml
- bundle/manifests/keda.sh_scaledobjects.yaml
- bundle/manifests/keda.sh_triggerauthentications.yaml
- config/default/kustomization.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/keda-olm-operator.clusterserviceversion.yaml
- keda/2.0.0/bundle.Dockerfile
- keda/2.0.0/manifests/keda-olm-operator.clusterserviceversion.yaml
- keda/2.0.0/manifests/keda-olm-operator_v1_serviceaccount.yaml
- keda/2.0.0/manifests/keda.sh_kedacontrollers.yaml
- keda/2.0.0/manifests/keda.sh_scaledjobs.yaml
- keda/2.0.0/manifests/keda.sh_scaledobjects.yaml
- keda/2.0.0/manifests/keda.sh_triggerauthentications.yaml
- main.go
- version/version.go
Updated to operator-sdk v1.1.0 and converted resources to a bundle format #27 
continuation of #44
> fixed issues from review

- .github/workflows/master-build.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/pr-tests.yml
- Makefile
- config/testing/catalog.yaml
- config/testing/crds.yaml
- config/testing/namespace.yaml
- config/testing/olm.yaml
- config/testing/operator_group.yaml
- config/testing/subscription.yaml
- controllers/kedacontroller_controller_test.go
- controllers/suite_test.go
- fixed e2e tests
- deploy KEDA olm operator from OperatorHub test
> Catalog test

- Makefile
> bundle-push: validate should happen before push

- .github/workflows/master-build.yml
Download opm in master-build github action
> download opm in master-build action

- .github/workflows/master-build.yml
Removed sudo from master-build github action
> removed sudo from master-build action

- Makefile
Comments-out 'replaces' in testing bundle
> comment out 'replaces' in testing bundle

- .github/workflows/master-build.yml
- Makefile
- bundle/manifests/keda.clusterserviceversion.yaml
- config/manifests/bases/keda.clusterserviceversion.yaml
Reworked testing in master build github action
> Rework master build

- .github/workflows/master-build.yml
Small change in master-build github action
> masater-build action fix

- .github/workflows/master-build.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/pr-tests.yml
- Dockerfile
> bump to Golang 1.15.6

- controllers/kedacontroller_controller.go
> resolve resource path from version

- config/default/kustomization.yaml
> use master version

- Dockerfile
- Makefile
> propagate Version to the docker build correctly

- keda/2.1.0/manifests/keda.v2.1.0.clusterserviceversion.yaml
> fix date format

- .github/workflows/master-build.yml
- Makefile
- config/testing/catalog.yaml
fix master-build github action
small fix in Makefile
change of version in CatalogSource manifest
> master-build action fix

- controllers/kedacontroller_controller.go
- resources/resources_handler.go
Fix bad handling of resources file path [here](https://github.com/kedacore/keda-olm-operator/blob/master/controllers/kedacontroller_controller.go#L81) 
> resources path file fix

- .github/workflows/master-build.yml
- .github/workflows/release-build.yml
- Makefile
- bundle/manifests/keda.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/manifests/bases/keda.clusterserviceversion.yaml
- config/testing/catalog.yaml
> Migrate to ghcr.io

- Dockerfile
> fixing resources.yaml path

- PROJECT
Convert PROJECT config from version 3-alpha to 3
> Convert PROJECT config from version 3-alpha to 3

- RELEASE-PROCESS.MD
> Update release process doc

- keda/1.4.1/metadata/annotations.yaml
- keda/1.5.0/metadata/annotations.yaml
- keda/2.0.0/metadata/annotations.yaml
- keda/2.1.0/metadata/annotations.yaml
- keda/2.2.0/metadata/annotations.yaml
- keda/2.3.0/metadata/annotations.yaml
> fix metadata to not include link to a missing scorecard

- .github/workflows/main-build.yml
- Makefile
- README.md
- bundle/manifests/keda-olm-operator_v1_serviceaccount.yaml
- bundle/manifests/keda.clusterserviceversion.yaml
- bundle/manifests/keda.sh_clustertriggerauthentications.yaml
- bundle/manifests/keda.sh_kedacontrollers.yaml
- bundle/manifests/keda.sh_scaledjobs.yaml
- bundle/manifests/keda.sh_scaledobjects.yaml
- bundle/manifests/keda.sh_triggerauthentications.yaml
- config/manager/manager.yaml
- config/manifests/bases/keda.clusterserviceversion.yaml
- config/testing/catalog.yaml
- version/version.go
> master -> main migration

- .github/workflows/main-build.yml
- .github/workflows/nightly-tests.yml
- Dockerfile
> bump to go 1.15.13

- Dockerfile
- Makefile
> don't include .git into build dockerfile

- config/default/kustomization.yaml
- config/manager/kustomization.yaml
> add image tag to kustomization

- README.md
- apis/keda/v1alpha1/kedacontroller_types.go
- config/crd/bases/keda.sh_kedacontrollers.yaml
- config/samples/keda_v1alpha1_kedacontroller.yaml
- controllers/keda/kedacontroller_controller.go
- controllers/keda/transform/transform.go
- hack/kedacontroller.yaml
> Allow setting priorityClassName

- RELEASE-PROCESS.MD
> update release process

- .github/workflows/main-build.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/pr-tests.yml
- Dockerfile
> bump golangci to 1.42.0 and Golang to 1.16.7

- .github/workflows/main-build.yml
> fix go version

- README.md
- config/samples/keda_v1alpha1_kedacontroller.yaml
- hack/kedacontroller.yaml
> Fix requests & limits sample

- controllers/keda/configmap_controller.go
- controllers/keda/kedacontroller_controller.go
- controllers/keda/kedacontroller_finalizer.go
- controllers/keda/secret_controller.go
- controllers/keda/util/util.go
> propagate context properly

- .github/workflows/main-build.yml
- .github/workflows/release-build.yml
- Makefile
> sign images with cosign and drop DockerHub support

- Makefile
> fix cosign

- RELEASE-PROCESS.MD
> update release notes

- .github/workflows/main-build.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/pr-tests.yml
- .github/workflows/release-build.yml
- bundle/manifests/keda.clusterserviceversion.yaml
> update actions and fix the general bundle

- .github/workflows/main-build.yml
- .github/workflows/release-build.yml
> use build-tools image from ghcr.io

- Dockerfile
> bump go to 1.17.10

- .github/workflows/main-build.yml
- .github/workflows/nightly-tests.yml
- Dockerfile
- bundle/manifests/keda.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> 65532 is numeric for nonroot

- .github/workflows/main-build.yml
- README.md
- apis/keda/v1alpha1/kedacontroller_types.go
- bundle/manifests/keda.clusterserviceversion.yaml
- config/crd/bases/keda.sh_kedacontrollers.yaml
- config/manager/manager.yaml
- config/manifests/bases/keda.clusterserviceversion.yaml
- config/rbac/role.yaml
- config/samples/keda_v1alpha1_kedacontroller.yaml
- controllers/keda/kedacontroller_controller.go
- controllers/keda/transform/transform.go
- hack/kedacontroller.yaml
- keda/2.7.1/manifests/keda.v2.7.1.clusterserviceversion.yaml
- resources/keda.yaml
> add `operator.logTimeEncoding`

- keda/2.7.1/manifests/keda.sh_kedacontrollers.yaml
> update crd for 2.7.1

- keda/2.7.1/manifests/keda.sh_kedacontrollers.yaml
- keda/2.7.1/manifests/keda.v2.7.1.clusterserviceversion.yaml
> fix 2.7.1 bundle

- controllers/keda/kedacontroller_controller.go
- controllers/keda/transform/transform.go
This allows a CSV to specify `KEDA_OPERATOR_IMAGE` and/or `KEDA_METRICS_SERVER_IMAGE` in the operator's deployment in order to use an alternate set of controllers.
> Allow operand images to be specified by env vars

- .github/workflows/main-build.yml
- sync cosign with kedacore/keda (fix main build)
> fix: main build workflow -> sync w/ keda - cosign

- .github/workflows/main-build.yml
*fix main build*
add:
- create cluster & keda ns
- olm operator
> fix: main-build.yaml add cluster,olm, keda ns

- .github/workflows/version-diff.yml
add new workflow that outputs diff of 2 last keda versions whenever there are changes to the `keda/` directory
> feat: add new GH workflow for versions diff

- config/manager/manager.yaml
> increasing memory limit to 1000Mi

- .github/workflows/main-build.yml
- Makefile
fix main-build workflow by adding kustomize binary to latest jobs in the workflow
> fix main-build

- .github/workflows/version-diff.yml
Update version-diff workflow file:
- add checker for `resources/keda.yaml` file
> Update version-diff workflow

- keda/2.8.2/manifests/keda.v2.8.2.clusterserviceversion.yaml
- keda/2.9.3/manifests/keda.v2.9.3.clusterserviceversion.yaml
Relates https://github.com/kedacore/keda-olm-operator/issues/162
> set memory limits to 1000Mi

- keda/2.9.3/manifests/keda.v2.9.3.clusterserviceversion.yaml
> KEDA >= 2.9 requires k8s version: 1.23

- README.md
- hack/kedacontroller.yaml
add examples to audit logging to readme & hack/
> add examples of audit loggging 

- resources/keda-olm-operator.yaml
> Add servicemonitor for webhooks pod, rename servicemonitor for keda operator

- bundle/manifests/keda.clusterserviceversion.yaml
- config/manifests/bases/keda.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/keda/kedacontroller_controller.go
- keda/2.10.1/manifests/keda.v2.10.1.clusterserviceversion.yaml
> Fix apiservice permissions broken during rebase

- bundle/manifests/keda.clusterserviceversion.yaml
- bundle/manifests/keda.sh_kedacontrollers.yaml
- config/manager/manager.yaml
- main.go
> watch only a single namespace

- .github/workflows/main-build.yml
> Make Deploy-test more robust

- .github/workflows/main-build.yml
- .github/workflows/nightly-tests.yml
> Properly run OLM install script

- hack/relprep.sh
Automatically performs many of the steps listed in
[RELEASE-PROCESS.md](https://github.com/kedacore/keda-olm-operator/blob/main/RELEASE-PROCESS.md)
> Add script to perform release chores

- README.md
- config/samples/keda_v1alpha1_kedacontroller.yaml
- hack/kedacontroller.yaml
> chore: typo `resourcesKedaOperator` -> `resources`

- .github/workflows/main-build.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/pr-tests.yml
- .github/workflows/release-build.yml
- .github/workflows/version-diff.yml
Also, update to latest github actions versions
> Perform test image build PR check

- controllers/keda/kedacontroller_controller.go
Any changes to the audit policy in the kedacontroller object are not compared to the configmap which is supposed to be derived from it. This means that creating an audit policy the first time works fine, but changing it doesn't (without manual intervention, such as deleting the configmap so it can be re-created with the new values). This change compares the current and expected values, and forces an update if they differ.
> Reconcile changes to audit policy

- go.mod
- go.sum
> Update golang.org/x/oauth2 for CVE-2025-22868

- keda/2.16.1/manifests/eventing.keda.sh_cloudeventsources.yaml
- keda/2.16.1/manifests/eventing.keda.sh_clustercloudeventsources.yaml
- keda/2.16.1/manifests/keda.sh_clustertriggerauthentications.yaml
- keda/2.16.1/manifests/keda.sh_kedacontrollers.yaml
- keda/2.16.1/manifests/keda.sh_scaledjobs.yaml
- keda/2.16.1/manifests/keda.sh_scaledobjects.yaml
- keda/2.16.1/manifests/keda.sh_triggerauthentications.yaml
- keda/2.16.1/manifests/keda.v2.16.1.clusterserviceversion.yaml
- keda/2.16.1/metadata/annotations.yaml
Oops, forgot to include the 2.16.1 manifests
> Prepare release 2.16.1 - part 2

- internal/controller/keda/kedacontroller_controller.go
Bug fix for nil namespace causing a panic when trying to add annotation.
> Fix: nil namespace error
